name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

jobs:
  # First job: clean up previous deployments
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete gh-pages branch if it exists
        run: |
          git fetch origin
          if git ls-remote --heads origin gh-pages | grep gh-pages; then
            git push origin --delete gh-pages || echo "Branch not found or already deleted"
          else
            echo "Branch gh-pages does not exist, skipping deletion"
          fi

  # Second job: build and deploy
  build-and-deploy:
    needs: cleanup
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Set environment variables for Next.js
          echo "NEXTAUTH_URL=https://tarang07q.github.io/Apt_Fincare" >> .env.production
          echo "NEXTAUTH_SECRET=TWPJQGsS1m1Q59Ts1AIgqMbnPBQy+b8zdyWz/zVILFs=" >> .env.production
          echo "RESEND_API_KEY=dummy_key_for_static_build" >> .env.production

          # Build the application
          npm run build
        env:
          NODE_ENV: production

      - name: Add .nojekyll file and modify HTML
        run: |
          touch out/.nojekyll
          mkdir -p scripts
          node scripts/modify-html.js || echo "Failed to modify HTML, continuing anyway"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true
          force: true
